apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: module-network
  description: Create VPC, Subnet and IP aliases
  tags:
    - hcl
spec:
  type: library
  lifecycle: experimental
  owner: choste
